#!/bin/sh


# -------------------------------------------ShiftIdentity.AspNetCore-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftEntity\\ShiftEntity.Web\\ShiftEntity.Web.csproj" \\/d' ShiftIdentity.AspNetCore/ShiftIdentity.AspNetCore.csproj
sed -i '/<ProjectReference Include="..\\..\\TypeAuth\\TypeAuth.Core\\TypeAuth.Core.csproj" \\/d' ShiftIdentity.AspNetCore/ShiftIdentity.AspNetCore.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftEntity\\\\ShiftEntity.Web\\\\ShiftEntity.Web.csproj\" \\/>/d" ShiftIdentity.AspNetCore/ShiftIdentity.AspNetCore.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\TypeAuth\\\\TypeAuth.Core\\\\TypeAuth.Core.csproj\" \\/>/d" ShiftIdentity.AspNetCore/ShiftIdentity.AspNetCore.csproj

# Stage the modified file
git add ShiftIdentity.AspNetCore/ShiftIdentity.AspNetCore.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------


# -------------------------------------------ShiftIdentity.Core-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftEntity\\ShiftEntity.Core\\ShiftEntity.Core.csproj" \\/d' ShiftIdentity.Core/ShiftIdentity.Core.csproj
sed -i '/<ProjectReference Include="..\\..\\TypeAuth\\TypeAuth.Core\\TypeAuth.Core.csproj" \\/d' ShiftIdentity.Core/ShiftIdentity.Core.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftEntity\\\\ShiftEntity.Core\\\\ShiftEntity.Core.csproj\" \\/>/d" ShiftIdentity.Core/ShiftIdentity.Core.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\TypeAuth\\\\TypeAuth.Core\\\\TypeAuth.Core.csproj\" \\/>/d" ShiftIdentity.Core/ShiftIdentity.Core.csproj

# Stage the modified file
git add ShiftIdentity.Core/ShiftIdentity.Core.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------




# -------------------------------------------ShiftIdentity.Dashboard.AspNetCore-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftEntity\\ShiftEntity.EFCore.SqlServer\\ShiftEntity.EFCore.SqlServer.csproj" \\/d' ShiftIdentity.Dashboard.AspNetCore/ShiftIdentity.Dashboard.AspNetCore.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftEntity\\\\ShiftEntity.EFCore.SqlServer\\\\ShiftEntity.EFCore.SqlServer.csproj\" \\/>/d" ShiftIdentity.Dashboard.AspNetCore/ShiftIdentity.Dashboard.AspNetCore.csproj

# Stage the modified file
git add ShiftIdentity.Dashboard.AspNetCore/ShiftIdentity.Dashboard.AspNetCore.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------



# -------------------------------------------ShiftIdentity.Core-----------------------------------------------------------------------------------------------

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\ShiftBlazor\\ShiftBlazor\\ShiftBlazor.csproj" \\/d' ShiftIdentity.Dashboard.Blazor/ShiftIdentity.Dashboard.Blazor.csproj
sed -i '/<ProjectReference Include="..\\..\\TypeAuth\\TypeAuth.Blazor\\TypeAuth.Blazor.csproj" \\/d' ShiftIdentity.Dashboard.Blazor/ShiftIdentity.Dashboard.Blazor.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\ShiftBlazor\\\\ShiftBlazor\\\\ShiftBlazor.csproj\" \\/>/d" ShiftIdentity.Dashboard.Blazor/ShiftIdentity.Dashboard.Blazor.csproj
sed -i "/<ProjectReference Include=\"..\\\\..\\\\TypeAuth\\\\TypeAuth.Blazor\\\\TypeAuth.Blazor.csproj\" \\/>/d" ShiftIdentity.Dashboard.Blazor/ShiftIdentity.Dashboard.Blazor.csproj

# Stage the modified file
git add ShiftIdentity.Dashboard.Blazor/ShiftIdentity.Dashboard.Blazor.csproj

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------