trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

 - script: dotnet build ShiftIdentity.Blazor --configuration release
   displayName: 'dotnet build ShiftIdentity.Blazor'

 - script: dotnet pack ShiftIdentity.Blazor --configuration release --output $(Build.ArtifactStagingDirectory)
   displayName: 'dotnet pack'

 - task: NuGetCommand@2
   condition: contains(variables['Build.SourceBranch'], 'refs/tags/release')  
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'